version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
  app:
    build: docker/elixir
    tty: true
    stdin_open: true
    volumes:
      - .:/opt/app
    ports:
      - 4000:4000
    depends_on:
      - db
    command: iex -S mix phx.server
    environment:
      NODE_ENV: 'development'
      POSTGRES_DB: 'app_dev'
      POSTGRES_HOST: db
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      TZ: 'Asia/Tokyo'
